package com.github.nridenko.likeorm.sample.manytomany.db.schema;

import com.github.nrudenko.orm.commons.DbType;
import com.github.nrudenko.orm.commons.Column;


/* AUTO-GENERATED FILE. CAREFUL TO MODIFY.
 *
 * This class was automatically generated by the
 * OrmGeneratorPlugin any changes will be overwritten
 * after next schema auto-generation
 */

public final class CompanyEmployeeScheme {

    public static final Column _ID = new Column("CompanyEmployee._id",  DbType.INT); // PRIMARY AUTOINCREMENT
    public static final Column COMPANY_ID = new Column("CompanyEmployee.companyId",  DbType.INT);
    public static final Column EMPLOYEE_ID = new Column("CompanyEmployee.employeeId",  DbType.INT);

}