package com.github.nridenko.likeorm.sample.manytomany.db.schema;

import com.github.nrudenko.orm.commons.DbType;
import com.github.nrudenko.orm.commons.Column;


/* AUTO-GENERATED FILE. CAREFUL TO MODIFY.
 *
 * This class was automatically generated by the
 * OrmGeneratorPlugin any changes will be overwritten
 * after next schema auto-generation
 */

public final class EmployeeScheme {

    public static final Column _ID = new Column("Employee._id",  DbType.INT); // PRIMARY AUTOINCREMENT
    public static final Column ID = new Column("Employee.id",  DbType.INT);
    public static final Column NAME = new Column("Employee.name",  DbType.TEXT);

}